### PR TITLE
Redirecting stdout and stderr in runner when executing the callables

### PR DESCRIPTION
**Pull request by mikicz**
I had no idea this existed, only learned about it yesterday at Pyvo. This solves one of the questions from the reviewer of the thesis.

### CODE REVIEW

**Comment by hroncok** [comment]
cc @MarekSuchanek

**Comment by hroncok** [comment]
Dos it work with C libs printfing? Or subprocess without pipe? If not, better document that.

**Comment by mikicz** [comment]
It doesn't work on subprocesses - I'll document it. Could you give me an example of some C lib that prints something?

**Comment by mikicz** [comment]
Thanks. Is the documentation I added about it sufficient or should I mention the C libs stuff as well?

**Review by hroncok — APPROVED** [review]

**Pull request merged**
